### ISSUE TITLE
Segmentation Fault in initMediaCapab

### ISSUE THREAD

**Issue by BCornelsen** [Tereius/ONVIFMonitor#2]
Hello,

If I add a camera, I get a segmentation fault at `0x0008152c in Device::initMediaCapab (this=0x5495c8) at /home/pi/Development/ONVIFMonitor/src/Device.cpp:412`.
The following code will be executed in this line:  `if(streamingCapa) service.setNoRTSPStreaming(*streamingCapa->NoRTSPStreaming);`

About my system:
OS: Raspbian GNU/Linux 10 (buster)
System: Raspberry PI 4

Best Regards,
Bastian

**Comment by wallerka77** [comment]
Hello,
I made the same experience.

Walter

**Comment by Tereius** [comment]
Hi,
should be fixed now.
